= Title
Sun Qian <fredsuvn@163.com>
:encoding: UTF-8
:license: https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license]
:emaill: fredsuvn@163.com
:url: https://github.com/srclab-projects/srclab-template

== Section

Word phrases 'enclosed in single quote characters' (acute accents) or _underline characters_ are emphasized.

Word phrases *enclosed in asterisk characters* are rendered in a strong font (usually bold).

Word phrases +enclosed in plus characters+ are rendered in a monospaced font.
Word phrases `enclosed in backtick characters` (grave accents) are also rendered in a monospaced font but in this case the enclosed text is rendered literally and is not subject to further expansion

Phrases enclosed with a `single grave accent to the left and a single acute accent to the right' are rendered in single quotation marks.

Phrases enclosed with ``two grave accents to the left and two acute accents to the right'' are rendered in quotation marks.

Placing #hashes around text# does nothing, it is a mechanism to allow inline attributes to be applied to otherwise unformatted text.

[red]#Obvious# and [big red yellow-background]*very obvious*.
[underline]#Underline text#, [overline]#overline text# and
[blue line-through]*bold blue and line-through*.

Unconstrained quotes have no boundary constraints and can be placed anywhere within inline text.
For consistency and to make them easier to remember unconstrained quotes are double-ups of the _, *, + and # constrained quotes:

__unconstrained emphasized text__ **unconstrained strong text**
++unconstrained monospaced text++
##unconstrained unquoted text## The following example emboldens the letter F:

**F**ile Open...

Put ^carets on either^ side of the text to be superscripted, put ~tildes on either side~ of text to be subscripted.
For example, the following line:

e^&#960;i^+1 = 0. H~2~O and x^10^.
Some ^super text^ and ~some sub text~

The following replacements are defined in the default AsciiDoc configuration:

(C) copyright, (TM) trademark, (R) registered trademark,
-- em dash, ... ellipsis, -> right arrow, <- left arrow, => right double arrow, <= left double arrow.

<<float>>

[[float]]
== The second day ==

[literal]
Consul *necessitatibus* per id, consetetur, eu pro everti postulant homero verear ea mea, qui.

TIP, NOTE, IMPORTANT, WARNING and CAUTION admonishment paragraph styles are generated by placing NOTE:, TIP:, IMPORTANT:, WARNING: or CAUTION: as the first word of the paragraph.
For example:

NOTE: This is an example note.
Alternatively, you can specify the paragraph admonition style explicitly using an AttributeList element.
For example:

[NOTE]
This is an example note.

[icons=None,caption="My Special Note"]
NOTE: This is my special note.

NOTE: This is my special note.

---------------------
CommentBlock:     //////////////////////////
PassthroughBlock: ++++++++++++++++++++++++++
ListingBlock:     --------------------------
LiteralBlock:     ..........................
SidebarBlock:     **************************
QuoteBlock:       __________________________
ExampleBlock:     ==========================
OpenBlock:        --
---------------------

[width="15%"]
|=======
|1 |2 |A
|3 |4 |B
|5 |6 |C
|=======

.An example table
[width="50%",cols=">s,^m,e",frame="topbot",options="header,footer"]
|==========================
|      2+|Columns 2 and 3
|1       |Item 1  |Item 1
|2       |Item 2  |Item 2
|3       |Item 3  |Item 3
|4       |Item 4  |Item 4
|footer 1|footer 2|footer 3
|==========================

.Windtrainer workouts
[width="80%",cols="3,^2,^2,10",options="header"]
|=========================================================
|Date |Duration |Avg HR |Notes

|22-Aug-08 |10:24 | 157 |
Worked out MSHR (max sustainable heart rate) by going hard for this interval.

|22-Aug-08 |23:03 | 152 |
Back-to-back with previous interval.

|24-Aug-08 |40:00 | 145 |
Moderately hard interspersed with 3x 3min intervals (2min hard + 1min really hard taking the HR up to 160).

|=========================================================

//[format="csv",cols="^1,4*2",options="header"]
//|===================================================
//ID,Customer Name,Contact Name,Customer Address,Phone
//include::customers.csv[]
//|===================================================