/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package demo.app

import kotlin.test.Test
import kotlin.test.*

class MessageUtilsTest {
    @Test
    fun testGetMessage() {
        assertEquals("Hello      World!", MessageUtils.getMessage())
    }
}